### ISSUE TITLE
Yuoki compatibility

### ISSUE THREAD

**Issue by BorisEagle** [kingarthur91/PyCoalTBaA#5]
Please note that previous versions of PyCoalTBaA were almost fully (except a couple of dublicates in pellets etc.) compatible with Bob+Angels+Yuoki mods, it will be great to retain compatibility.

**Comment by ZXQWAS** [comment]
There was never a compatibility patch for Yuoki. It was just compatible because almost nothing in them conflicted. There are item/recipe duplicates, but it's not critical. Yuoki can be played within ABPy as a separate minigame. I have it, but haven't tried myself yet. Yuoki _really_ doesn't make sense. :)

**Comment by BorisEagle** [comment]
I like Yuoki mod, 600+ hours played, have perfect sense for me :) As far as I understood, this issues list is some kind of a "wish list", of course when code of PyCoalTBaA will be refactored by KingArthur anyone can fork it to add their favored mods compatibility.

**Comment by kingarthur91** [comment]
as was stated yuoki was never "made" compatible as such nothing i do should break it. i will at a later point look into and anyone else is welcome to send me info on duplicates and the like or make pull request to add compatibility.
